---
- name: "ğŸ”„ Apt Cache aktualisieren"
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: "ğŸ†™ System Upgrade (dist-upgrade)"
  apt:
    upgrade: dist

- name: "ğŸ› ï¸ Basispakete installieren"
  apt:
    name:
      - vim
      - curl
      - git
      - htop
      - net-tools
      - wget
      - python3-pip
      - python3-docker # WICHTIG fÃ¼r Ansible Docker Module
    state: present

- name: "ğŸ“¦ Ansible Docker Collection installieren"
  command: ansible-galaxy collection install community.docker
  delegate_to: localhost 
  ignore_errors: yes 
