---
# User Konfiguration
admin_username: admin_user
admin_shell: /bin/bash
admin_groups: "sudo"

# Pfad zum Public Key (LOKAL auf dem Controller/WSL)
# Wir erwarten, dass das setup_prod_env.sh Skript diesen Key erzeugt hat.
ssh_key_path: "{{ role_path }}/files/id_rsa_prod.pub"
